version = 1

[[analyzers]]
name = "shell"

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "19"
  language_version = "1.9"

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = ["actions.yml"]