version = 1

test_patterns = [".deepsource.toml"]

[[analyzers]]
name = "shell"

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "19"
  language_version = "1.9"

[[analyzers]]
name = "docker"

  [analyzers.meta]
  dockerfile_paths = ["actions.yml"]

[[transformers]]
name = "ktlint"